### ISSUE TITLE
Tjek app-store for konkurenter

### ISSUE THREAD

**Issue by andracs** [andracs/Eeny-meeny#2]

**Comment by ande7195** [comment]
https://longurlmaker.com/go?id=3wShortURL205farZoff1brangyexpandeda0wrgz9Ulimitcontinued60sustainedWapURLYepItstretcheenduring5SnipURL1rangy0olastinga911distantbRubyURL128CanURL0o204ShrinkURL101cstretchedFly279IsZgd31enduring756uB654ShortURLfUrlTeay140GetShorty1ShortURL4xenduring1Ne18ShortURLlqoutstretched6s0ShortenURLfarZreaching9164CanURL619FhURL2ld43f0YepItx804ckShortURLlingering1stretchedlengthy0enduringstretchB650tallenduring4051farZreachingdNutshellURL141stringyi70Ne14lengthenedBeamZto8lingeringlankyprolonged9stretchedUlimit00b1lqtowering14rangy1continuedb07drawnZout144spreadZoutstretching5qd1Ulimitlanky1tlengthyh9u19d0outstretched0deepGetShortystretchinglongishrunning621EasyURL09ShortURL006URLGetShortylasting0w4u11ShortenURL18z1lofty0gh07YepIt0longish730ShredURL15Sitelutionsip0Metamark20stretching191CanURLremoteDecentURLa14DecentURLUlimitDwarfurlURLHawkUlimit4Dwarfurl6ShortenURLSitelutionslongish0u21fdudrawnZout9aDwarfurlBeamZtoShortURLdwYepIt0spunZout41dbdrawnZoutXZsew754v0a1cTinyLinkaTightURL2011eRubyURLDwarfurlG8Lb210enlarged5f8927fShrinkURL5cUlimit02rgangling71ganglingfarawaylofty10stretchingXil7outstretchedprotracted0loftyyc9outstretched1z74s028distantShortenURL58DigBigfprolonged9A2N7438Minilien7b0B65109enduring10ShortURL00DigBig300ShrinkURLdShortURL751301URL6UlimitUrlTeafURLZcoZuklengthenedr61upYATUC0stringyEasyURL18MyURLbURLcut3b0s531871URLviIsZgd80Dwarfurl11sustainedShortenURL01003554enlarged1drawnZout1964o8URLcut6farawayStartURLIsZgd05433lenlargedrunningSitelutions0IsZgdoutstretched70d92dprolonged502s01yiShoterLink6sURLcut640running5oShortlinks1DecentURL951508RedirxelongatedStartURL1TinyURL30ae71kt1917stretched51a8095945deepBeamZtoeRubyURL60stretching1lengthenedlasting5farZoff1ohighkl3URLZcoZuk8WapURL10ShrinkURLlengthenedDoiop1lanky09TightURL01URLvi8b0protracted410SnipURLA2Nfarawaya16URLb150760StartURLTinyLink00b1Sitelutionslingering0GetShortyf27lasting96expandeddNanoRef6bf1spunZout20tallenlarged05YepIt15lfarZoff150aEasyURL7wIsZgdelongated85G8LTinyURLShorlUrlTea32GetShorty0hd9stretching0spunZout04LiteURLrangy185ac1tallca7lankyco

**Comment by jibauch94** [comment]
Google Play
Eeny, Meeny, Miny, Moe
https://play.google.com/store/apps/details?id=jp.gr.java_conf.qubit.eeny&hl=sw
	En app der tager forskellige input (strings) hvor den så vælger en af dine input.
Fx du ved ikke hvad du skal drikke (kaffe, the, cola, vand), disse skriver du som inputs, og trykker på knappen eeny, meeny, miny, mo og appen udvælger af dine inputs.

Eeny, meeny, miny, mo
https://play.google.com/store/apps/details?id=com.comosite.endendbar&hl=sw
Insert your dilemma, write down your option and let the fate decide for you. 
Good Luck!

**Comment by andracs** [comment]
Der er ingen killer apps i denne niche.
